// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqlskWkT7qdvb4bNA2xZxfYAM_hVITc9g',
    appId: '1:924109842758:web:765b106f9c6890632b5d47',
    messagingSenderId: '924109842758',
    projectId: 'payamlater-7e7b6',
    authDomain: 'payamlater-7e7b6.firebaseapp.com',
    storageBucket: 'payamlater-7e7b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtrWERKZoASt3K8QNQDPSDFJMbWb_HzbU',
    appId: '1:924109842758:android:96c600f745a147ff2b5d47',
    messagingSenderId: '924109842758',
    projectId: 'payamlater-7e7b6',
    storageBucket: 'payamlater-7e7b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXrW_C7H-DazS988MXQA4t58M65-7_iaE',
    appId: '1:924109842758:ios:23eb9917a6134e242b5d47',
    messagingSenderId: '924109842758',
    projectId: 'payamlater-7e7b6',
    storageBucket: 'payamlater-7e7b6.appspot.com',
    iosClientId: '924109842758-akjtt68l3sb3p3tq07d9mdprnhmfu0jj.apps.googleusercontent.com',
    iosBundleId: 'com.lbb.payamlater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXrW_C7H-DazS988MXQA4t58M65-7_iaE',
    appId: '1:924109842758:ios:23eb9917a6134e242b5d47',
    messagingSenderId: '924109842758',
    projectId: 'payamlater-7e7b6',
    storageBucket: 'payamlater-7e7b6.appspot.com',
    iosClientId: '924109842758-akjtt68l3sb3p3tq07d9mdprnhmfu0jj.apps.googleusercontent.com',
    iosBundleId: 'com.lbb.payamlater',
  );
}
